ATTACKS = {
    "attack_light": {
        "damage": 12,
        "range": 82,
        "height": 40,
        "offset_y": 20,
        "stamina": 10,
        "knockback": 190,
        "startup": 0.07,
        "active": 0.09,
        "recovery": 0.16,
        "lunge": 56,
        "hitstop": 0.055,
    },
    "attack_heavy": {
        "damage": 20,
        "range": 102,
        "height": 58,
        "offset_y": 18,
        "stamina": 18,
        "knockback": 290,
        "startup": 0.16,
        "active": 0.11,
        "recovery": 0.27,
        "lunge": 82,
        "hitstop": 0.09,
    },
    "kick": {
        "damage": 10,
        "range": 86,
        "height": 46,
        "offset_y": 48,
        "stamina": 8,
        "knockback": 165,
        "startup": 0.10,
        "active": 0.12,
        "recovery": 0.18,
        "lunge": 68,
        "hitstop": 0.065,
    },
    "low_kick": {
        "damage": 11,
        "range": 92,
        "height": 28,
        "offset_y": 80,
        "stamina": 9,
        "knockback": 172,
        "startup": 0.08,
        "active": 0.11,
        "recovery": 0.18,
        "lunge": 54,
        "hitstop": 0.06,
        "requires_ground": True,
        "requires_crouch": True,
        "keep_crouch": True,
    },
    "flying_kick": {
        "damage": 14,
        "range": 96,
        "height": 40,
        "offset_y": 34,
        "stamina": 12,
        "knockback": 228,
        "startup": 0.05,
        "active": 0.12,
        "recovery": 0.2,
        "lunge": 260,
        "hitstop": 0.075,
        "requires_ground": False,
        "requires_air": True,
        "vertical_speed_cap": 190,
    },
}
