ATTACKS = {
    "attack_light": {
        "damage": 12,
        "range": 82,
        "height": 40,
        "offset_y": 20,
        "stamina": 10,
        "knockback": 190,
        "startup": 0.07,
        "active": 0.09,
        "recovery": 0.16,
        "lunge": 56,
        "hitstop": 0.055,
    },
    "attack_heavy": {
        "damage": 20,
        "range": 102,
        "height": 58,
        "offset_y": 18,
        "stamina": 18,
        "knockback": 290,
        "startup": 0.16,
        "active": 0.11,
        "recovery": 0.27,
        "lunge": 82,
        "hitstop": 0.09,
    },
    "kick": {
        "damage": 10,
        "range": 86,
        "height": 46,
        "offset_y": 48,
        "stamina": 8,
        "knockback": 165,
        "startup": 0.10,
        "active": 0.12,
        "recovery": 0.18,
        "lunge": 68,
        "hitstop": 0.065,
    },
}
